### ISSUE TITLE
Build error - Doesn't effect final build

### ISSUE THREAD

**Issue by dymurray** [fusor/ocp-velero-plugin#16]
Seeing this error when building the plugin container:

```
go: disabling cache (/go/.cache) due to initialization failure: mkdir /go/.cache: permission denied
```

**Comment by sseago** [comment]
It's a go issue: https://github.com/golang/go/issues/26280

It's already fixed upstream in go, but the fix is merely to suppress the warning in cases like this: https://go-review.googlesource.com/c/go/+/122487/

**Comment by sseago** [comment]
This was fixed with https://github.com/fusor/ocp-velero-plugin/pull/31
