### ISSUE TITLE
GetRegistryInfo fails on 3.x if a registry hostname is set

### ISSUE THREAD

**Issue by sseago** [fusor/ocp-velero-plugin#57]
In order to update local image references on restore we have to set an annotation with the local registry hostname for both backup and restore. For 4.x we can pull this from the APIServerConfig obtained via the openshift-apiserver ConfigMaps. This doesn't exist in 3.x, so for 3.11 and earlier we're just pulling the ClusterIP and Port from the internal registry service resource. This works when a hostname isn't set, but it fails when there's a configured hostname, since the local image references will use the hostname, and thus they'll never match the ClusterIP:port. `oc registry info` returns the right string in both cases on 3.x, so we need to determine how to obtain that information from the cluster via the client API and use this instead of the ip:port from the registry service.

**Comment by fbladilo** [comment]
@sseago Worked for me using your test images... :+1:
