### ISSUE TITLE
Break out client instantiation to it's own package

### ISSUE THREAD

**Issue by dymurray** [fusor/ocp-velero-plugin#8]
We are instantiating clients from hidden functions and ideally we break these out into it's own package since stuff like `imageClient` is reused everywhere.

We want an exported function in package `client` that gives us:
```
client, err := client.NewImageClient()
```

Do this for every client we instantiate and put it all under one package.

**Comment by sseago** [comment]
I'm starting this with the common and imagestream packages right now. I expect to have a PR some time tomorrow with the first parts of this in place.
